### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by hadess** [flathub/com.sublimetext.three.DevUtils#1]
This isn't really a valid license:
```
  <project_license>...</project_license>
```

At the very least, Free Software and non-Free Software should be split if necessary.

**Comment by ptomato** [comment]
All tools included are MIT-licensed except for yamllint, which is GPLv3. I'd be happy to accept a pull request for this. It must have been an oversight, I created the extension in a hurry as it was a last-minute review comment.
